config/routes.rb
Rails.application.routes.draw do
  resources :guestbook_messages
  root 'guestbook_messages#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  # https://stackoverflow.com/questions/78016964/ransack-needs-adminuser-attributes-explicitly-allowlisted-issue-in-rails-7-with
  def self.ransackable_attributes(auth_object = nil)
    @ransackable_attributes ||= column_names + _ransackers.keys + _ransack_aliases.keys + attribute_aliases.keys
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  # https://stackoverflow.com/questions/78016964/ransack-needs-adminuser-attributes-explicitly-allowlisted-issue-in-rails-7-with
  def self.ransackable_attributes(auth_object = nil)
    @ransackable_attributes ||= column_names + _ransackers.keys + _ransack_aliases.keys + attribute_aliases.keys
  end
end

app/models/guestbook_message.rb
class GuestbookMessage < ApplicationRecord
  paginates_per 10

  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guestbook_messages_controller.rb
class GuestbookMessagesController < InheritedResources::Base
  # Disable form token verification
  skip_before_action :verify_authenticity_token

  actions :all, :except => [ :show, :edit, :update, :destroy ]

  def create
    @guestbook_message = GuestbookMessage.new(guestbook_message_params)
    @guestbook_message.ip = request.ip
    @guestbook_message.remote_ip = request.remote_ip
    @guestbook_message.user_agent = request.user_agent
    create!
  end

  private

    def guestbook_message_params
      params.require(:guestbook_message).permit(:name, :text)
    end

    # https://github.com/activeadmin/inherited_resources#:~:text=want%20to%20add-,pagination,-to%20your%20projects
    def collection
      get_collection_ivar || set_collection_ivar(end_of_association_chain.order('created_at desc').page(params[:page]))
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbook_messages_helper.rb
module GuestbookMessagesHelper
end

app/views/guestbook_messages/_form.html.erb
<%= form_with(model: guestbook_message) do |form| %>
  <% if guestbook_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guestbook_message.errors.count, "error") %> prohibited this guestbook_message from being saved:</h2>

      <ul>
        <% guestbook_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guestbook_messages/_guestbook_message.html.erb
<div id="<%= dom_id guestbook_message %>">
  <p>
    <strong>Name:</strong>
    <%= guestbook_message.name %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= guestbook_message.text %>
  </p>

  <p>
    <strong>Ip:</strong>
    <%= guestbook_message.ip %>
  </p>

  <p>
    <strong>Remote ip:</strong>
    <%= guestbook_message.remote_ip %>
  </p>

  <p>
    <strong>User agent:</strong>
    <%= guestbook_message.user_agent %>
  </p>

</div>

app/views/guestbook_messages/edit.html.erb
<h1>Editing guestbook message</h1>

<%= render "form", guestbook_message: @guestbook_message %>

<br>

<div>
  <%= link_to "Show this guestbook message", @guestbook_message %> |
  <%= link_to "Back to guestbook messages", guestbook_messages_path %>
</div>

app/views/guestbook_messages/index.html.erb
<p><%= paginate @guestbook_messages %></p>

<p style="color: green"><%= notice %></p>

<h1>Guestbook messages</h1>

<div id="guestbook_messages">
  <% @guestbook_messages.each do |guestbook_message| %>
    <%= render guestbook_message %>
    <p>
      <% # = link_to "Show this guestbook message", guestbook_message %>
    </p>
    <hr/>
  <% end %>
</div>

<%= link_to "New guestbook message", new_guestbook_message_path %>

<p><%= paginate @guestbook_messages %></p>

app/views/guestbook_messages/new.html.erb
<h1>New guestbook message</h1>

<%= render "form", guestbook_message: @guestbook_message %>

<br>

<div>
  <%= link_to "Back to guestbook messages", guestbook_messages_path %>
</div>

app/views/guestbook_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @guestbook_message %>

<div>
  <%= link_to "Edit this guestbook message", edit_guestbook_message_path(@guestbook_message) %> |
  <%= link_to "Back to guestbook messages", guestbook_messages_path %>

  <%= button_to "Destroy this guestbook message", @guestbook_message, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSandbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <% # = javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>